message(STATUS "finding socketor")

FIND_PATH(SOCKETOR_INCLUDE_DIR socketor.h ${CMAKE_MODULE_PATH}/include)
message(STATUS "include dir: ${SOCKETOR_INCLUDE_DIR}")

FIND_LIBRARY(SOCKETOR_LIBRARY socketor ${CMAKE_MODULE_PATH}/)
message(STATUS "socketor lib dir: ${SOCKETOR_LIBRARY}")


if(SOCKETOR_INCLUDE_DIR AND SOCKETOR_LIBRARY)
    set(SOCKETOR_FOUND TRUE)
    include_directories(${SOCKETOR_INCLUDE_DIR})
endif(SOCKETOR_INCLUDE_DIR AND SOCKETOR_LIBRARY)