message(STATUS "finding socketor")

FIND_PATH(SOCKETOR_INCLUDE_DIR socketor.h ${CMAKE_MODULE_PATH}/include)
message(STATUS "include dir: ${SOCKETOR_INCLUDE_DIR}")

FIND_LIBRARY(CLIENT_LIBRARY sockclient ${CMAKE_MODULE_PATH}/)
message(STATUS "client lib dir: ${CLIENT_LIBRARY}")

FIND_LIBRARY(SERVER_LIBRARY sockserver ${CMAKE_MODULE_PATH}/)
message(STATUS "server lib dir: ${SERVER_LIBRARY}")

if(SOCKETOR_INCLUDE_DIR AND CLIENT_LIBRARY AND SERVER_LIBRARY)
    set(SOCKETOR_FOUND TRUE)
    include_directories(${SOCKETOR_INCLUDE_DIR})
endif(SOCKETOR_INCLUDE_DIR AND CLIENT_LIBRARY AND SERVER_LIBRARY)